name: mpcstats

on:
  push:
    branches:
      - '*'

jobs:
  test-on-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the pushed branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install MP-SPDZ dependencies
        run: sudo apt-get install -y automake build-essential clang cmake git libboost-dev libboost-iostreams-dev libboost-thread-dev libgmp-dev libntl-dev libsodium-dev libssl-dev libtool

      - name: Set up MP-SPDZ
        run: make setup

      - name: Compile semi-party.x
        run: make -j8 semi-party.x

      - name: Run tests
        run: pytest -v
